version: "3.9" 

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node
    env_file:
      - ./backend/.env
    ports:
      - 50031:50031

  sfu:
    build:
      context: ./sfu
      dockerfile: Dockerfile
    container_name: sfu
    ports:
      - 50051:50051